server:
  port: 80
application:
  name: chenxing
spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    name: test
    url: jdbc:mysql://139.199.61.237:3306/chenxing?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: pdm920521
    driver-class-name: com.mysql.jdbc.Driver
    connectionProperties: useUnicode=true;autoReconnect=true;failOverReadOnly=false;characterEncoding=utf8;zeroDateTimeBehavior=convertToNull;allowMultiQueries=true
    initialSize: 50
    maxActive: 300
    minIdle: 50
    maxWait: 1000
    defaultAutoCommit: true
    timeBetweenEvictionRunsMillis: 600000
    numTestsPerEvictionRun: 3
    minEvictableIdleTimeMillis: 1800000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    validationQuery: select 1
    removeAbandoned: true
    removeAbandonedTimeout: 180
    logAbandoned: true
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  resources:
    static-locations: classpath:static/,file:/upload/
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.cx.chenxing.db.*.dao