server:
  port: 8001
application:
  name: chenxing
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/chenxing
    username: root
    password: pdm920521
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.cx.chenxing.*.dao