server:
  port: 8001
application:
  name: chenxing
spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    name: test
    url: jdbc:mysql://139.199.61.237:3306/chenxing?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: pdm920521
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.cx.chenxing.*.dao